### ISSUE TITLE
Scriptek futtatása nélkül is legyen válasz

### ISSUE THREAD

**Issue by Res42** [Res42/kisbigvan#3]
Ha le van tiltva az oldalon a scriptek futtatása, akkor nem jelenik meg válasz.

Büntessük meg ezeket az embereket azzal, hogy beégetjük a `Nem.` választ. A script pedig csak a "kisbig van" ágat kezelje le.

**Comment by zandraaperjesi** [comment]
Dolgoznék az issuen.
